accent = "#b3daf9"
cursor = "#b3daf9"
foreground = "#d8d4cd"
background = "#11262d"
selection_foreground = "#11262d"
selection_background = "#b3daf9"

color0  = "#051a20"
color1  = "#fac5c7"
color2  = "#b8e1c1"
color3  = "#d9d8aa"
color4  = "#b3daf9"
color5  = "#edc7e7"
color6  = "#a6e1e2"
color7  = "#d8d4cd"
color8  = "#2c4249"
color9  = "#fac5c7"
color10 = "#b8e1c1"
color11 = "#d9d8aa"
color12 = "#d1cffb"
color13 = "#edc7e7"
color14 = "#a6e1e2"
color15 = "#f4f0e9"
